version: '3.8'

services:
  schema-validator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - CHROMA_PERSIST_DIRECTORY=/app/chroma_db
      - REDIS_URL=redis://redis:6379/0
      # Add your AI provider API key here
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - AI_PROVIDER=${AI_PROVIDER:-openai}
    volumes:
      - chroma_data:/app/chroma_db
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Optional: Redis admin interface
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles:
      - admin

volumes:
  chroma_data:
  redis_data: 